CREATE TABLE IF NOT EXISTS `${ICEBERG_CATALOG_NAME}`.`${ICEBERG_NAMESPACE}`.`${ICEBERG_TABLE}` (
  event_timestamp TIMESTAMP_LTZ(3),
  event_date DATE,
  event_kind STRING,
  event_category ARRAY<STRING>,
  event_type ARRAY<STRING>,
  event_module STRING,
  event_dataset STRING,
  event_severity INT,
  message STRING,
  event_original STRING,
  source_ip STRING,
  source_port INT,
  source_bytes BIGINT,
  source_packets BIGINT,
  destination_ip STRING,
  destination_port INT,
  destination_bytes BIGINT,
  destination_packets BIGINT,
  related_ip ARRAY<STRING>,
  network_transport STRING,
  network_protocol STRING,
  network_bytes BIGINT,
  network_packets BIGINT,
  rule_id STRING,
  rule_name STRING,
  rule_category STRING,
  zeek_conn_uid STRING,
  zeek_conn_service STRING,
  zeek_conn_duration DOUBLE,
  zeek_conn_state STRING,
  zeek_conn_history STRING,
  zeek_conn_missed_bytes BIGINT,
  zeek_conn_local_orig BOOLEAN,
  zeek_conn_tunnel_parents ARRAY<STRING>,
  snort_generator_id INT,
  snort_signature_id INT,
  snort_signature_revision INT,
  snort_ip_ttl INT,
  snort_ip_tos STRING,
  snort_ip_id INT,
  snort_ip_len INT,
  snort_ip_flags STRING,
  snort_packet_len INT,
  snort_tcp_flags_raw STRING,
  snort_tcp_seq STRING,
  snort_tcp_ack STRING,
  snort_tcp_window STRING,
  snort_tcp_len INT,
  snort_xref STRING,
  log_file_path STRING
)
PARTITIONED BY (event_date, event_dataset)
WITH (
  'format-version' = '2',
  'write.format.default' = 'parquet',
  'write.parquet.compression-codec' = 'snappy',
  'write.distribution-mode' = 'hash'
);
