CREATE TEMPORARY TABLE zeek_conn_cold_src (
  `@timestamp` TIMESTAMP_LTZ(3),
  `event.kind` STRING,
  `event.category` ARRAY<STRING>,
  `event.type` ARRAY<STRING>,
  `event.module` STRING,
  `event.dataset` STRING,
  `source.ip` STRING,
  `source.port` INT,
  `source.bytes` BIGINT,
  `source.packets` BIGINT,
  `destination.ip` STRING,
  `destination.port` INT,
  `destination.bytes` BIGINT,
  `destination.packets` BIGINT,
  `network.transport` STRING,
  `network.protocol` STRING,
  `network.bytes` BIGINT,
  `network.packets` BIGINT,
  `related.ip` ARRAY<STRING>,
  `message` STRING,
  `event.original` STRING,
  `zeek.conn.uid` STRING,
  `zeek.conn.service` STRING,
  `zeek.conn.duration` DOUBLE,
  `zeek.conn.state` STRING,
  `zeek.conn.history` STRING,
  `zeek.conn.missed_bytes` BIGINT,
  `zeek.conn.local_orig` BOOLEAN,
  `zeek.conn.tunnel_parents` ARRAY<STRING>
) WITH (
  'connector' = 'kafka',
  'topic' = 'zeek.conn',
  'properties.bootstrap.servers' = '${KAFKA_BOOTSTRAP_SERVERS_INTERNAL}',
  'properties.group.id' = '${KAFKA_COLD_PATH_GROUP_ID_ZEEK}',
  'scan.startup.mode' = '${KAFKA_SCAN_STARTUP_MODE}',
  'format' = 'json',
  'json.ignore-parse-errors' = 'true',
  'json.timestamp-format.standard' = 'ISO-8601'
);

CREATE TEMPORARY TABLE snort_alert_cold_src (
  `@timestamp` TIMESTAMP_LTZ(3),
  `event.kind` STRING,
  `event.category` ARRAY<STRING>,
  `event.type` ARRAY<STRING>,
  `event.module` STRING,
  `event.dataset` STRING,
  `event.severity` INT,
  `rule.id` STRING,
  `rule.name` STRING,
  `rule.category` STRING,
  `source.ip` STRING,
  `source.port` INT,
  `destination.ip` STRING,
  `destination.port` INT,
  `network.transport` STRING,
  `related.ip` ARRAY<STRING>,
  `message` STRING,
  `event.original` STRING,
  `snort.generator_id` INT,
  `snort.signature_id` INT,
  `snort.signature_revision` INT,
  `snort.ip.ttl` INT,
  `snort.ip.tos` STRING,
  `snort.ip.id` INT,
  `snort.ip.len` INT,
  `snort.ip.flags` STRING,
  `snort.packet.len` INT,
  `snort.tcp.flags_raw` STRING,
  `snort.tcp.seq` STRING,
  `snort.tcp.ack` STRING,
  `snort.tcp.window` STRING,
  `snort.tcp.len` INT,
  `snort.xref` STRING,
  `log.file.path` STRING
) WITH (
  'connector' = 'kafka',
  'topic' = 'snort.alert',
  'properties.bootstrap.servers' = '${KAFKA_BOOTSTRAP_SERVERS_INTERNAL}',
  'properties.group.id' = '${KAFKA_COLD_PATH_GROUP_ID_SNORT}',
  'scan.startup.mode' = '${KAFKA_SCAN_STARTUP_MODE}',
  'format' = 'json',
  'json.ignore-parse-errors' = 'true',
  'json.timestamp-format.standard' = 'ISO-8601'
);
