SET 'execution.checkpointing.interval' = '${FLINK_CHECKPOINT_INTERVAL}';

INSERT INTO `${ICEBERG_CATALOG_NAME}`.`${ICEBERG_NAMESPACE}`.`${ICEBERG_TABLE}`
SELECT
  `@timestamp` AS event_timestamp,
  CAST(`@timestamp` AS DATE) AS event_date,
  `event.kind` AS event_kind,
  `event.category` AS event_category,
  `event.type` AS event_type,
  `event.module` AS event_module,
  `event.dataset` AS event_dataset,
  CAST(NULL AS INT) AS event_severity,
  `message`,
  `event.original` AS event_original,
  `source.ip` AS source_ip,
  `source.port` AS source_port,
  `source.bytes` AS source_bytes,
  `source.packets` AS source_packets,
  `destination.ip` AS destination_ip,
  `destination.port` AS destination_port,
  `destination.bytes` AS destination_bytes,
  `destination.packets` AS destination_packets,
  `related.ip` AS related_ip,
  `network.transport` AS network_transport,
  `network.protocol` AS network_protocol,
  `network.bytes` AS network_bytes,
  `network.packets` AS network_packets,
  CAST(NULL AS STRING) AS rule_id,
  CAST(NULL AS STRING) AS rule_name,
  CAST(NULL AS STRING) AS rule_category,
  `zeek.conn.uid` AS zeek_conn_uid,
  `zeek.conn.service` AS zeek_conn_service,
  `zeek.conn.duration` AS zeek_conn_duration,
  `zeek.conn.state` AS zeek_conn_state,
  `zeek.conn.history` AS zeek_conn_history,
  `zeek.conn.missed_bytes` AS zeek_conn_missed_bytes,
  `zeek.conn.local_orig` AS zeek_conn_local_orig,
  `zeek.conn.tunnel_parents` AS zeek_conn_tunnel_parents,
  CAST(NULL AS INT) AS snort_generator_id,
  CAST(NULL AS INT) AS snort_signature_id,
  CAST(NULL AS INT) AS snort_signature_revision,
  CAST(NULL AS INT) AS snort_ip_ttl,
  CAST(NULL AS STRING) AS snort_ip_tos,
  CAST(NULL AS INT) AS snort_ip_id,
  CAST(NULL AS INT) AS snort_ip_len,
  CAST(NULL AS STRING) AS snort_ip_flags,
  CAST(NULL AS INT) AS snort_packet_len,
  CAST(NULL AS STRING) AS snort_tcp_flags_raw,
  CAST(NULL AS STRING) AS snort_tcp_seq,
  CAST(NULL AS STRING) AS snort_tcp_ack,
  CAST(NULL AS STRING) AS snort_tcp_window,
  CAST(NULL AS INT) AS snort_tcp_len,
  CAST(NULL AS STRING) AS snort_xref,
  CAST(NULL AS STRING) AS log_file_path
FROM zeek_conn_cold_src
UNION ALL
SELECT
  `@timestamp` AS event_timestamp,
  CAST(`@timestamp` AS DATE) AS event_date,
  `event.kind` AS event_kind,
  `event.category` AS event_category,
  `event.type` AS event_type,
  `event.module` AS event_module,
  `event.dataset` AS event_dataset,
  `event.severity` AS event_severity,
  `message`,
  `event.original` AS event_original,
  `source.ip` AS source_ip,
  `source.port` AS source_port,
  CAST(NULL AS BIGINT) AS source_bytes,
  CAST(NULL AS BIGINT) AS source_packets,
  `destination.ip` AS destination_ip,
  `destination.port` AS destination_port,
  CAST(NULL AS BIGINT) AS destination_bytes,
  CAST(NULL AS BIGINT) AS destination_packets,
  `related.ip` AS related_ip,
  `network.transport` AS network_transport,
  CAST(NULL AS STRING) AS network_protocol,
  CAST(NULL AS BIGINT) AS network_bytes,
  CAST(NULL AS BIGINT) AS network_packets,
  `rule.id` AS rule_id,
  `rule.name` AS rule_name,
  `rule.category` AS rule_category,
  CAST(NULL AS STRING) AS zeek_conn_uid,
  CAST(NULL AS STRING) AS zeek_conn_service,
  CAST(NULL AS DOUBLE) AS zeek_conn_duration,
  CAST(NULL AS STRING) AS zeek_conn_state,
  CAST(NULL AS STRING) AS zeek_conn_history,
  CAST(NULL AS BIGINT) AS zeek_conn_missed_bytes,
  CAST(NULL AS BOOLEAN) AS zeek_conn_local_orig,
  CAST(NULL AS ARRAY<STRING>) AS zeek_conn_tunnel_parents,
  `snort.generator_id` AS snort_generator_id,
  `snort.signature_id` AS snort_signature_id,
  `snort.signature_revision` AS snort_signature_revision,
  `snort.ip.ttl` AS snort_ip_ttl,
  `snort.ip.tos` AS snort_ip_tos,
  `snort.ip.id` AS snort_ip_id,
  `snort.ip.len` AS snort_ip_len,
  `snort.ip.flags` AS snort_ip_flags,
  `snort.packet.len` AS snort_packet_len,
  `snort.tcp.flags_raw` AS snort_tcp_flags_raw,
  `snort.tcp.seq` AS snort_tcp_seq,
  `snort.tcp.ack` AS snort_tcp_ack,
  `snort.tcp.window` AS snort_tcp_window,
  `snort.tcp.len` AS snort_tcp_len,
  `snort.xref` AS snort_xref,
  `log.file.path` AS log_file_path
FROM snort_alert_cold_src;
